kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keycloak-pvc-development
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage" <change storage class>
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
~
